"""Add is_archived to conversations

Revision ID: fe184e27340c
Revises: c74f51e0db02
Create Date: 2026-05-22 20:22:44.276269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe184e27340c'
down_revision: Union[str, None] = 'c74f51e0db02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('ix_conversations_user_id_is_archived', 'conversations', ['user_id', 'is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_user_id_is_archived', table_name='conversations')
    op.drop_column('conversations', 'is_archived')
    # ### end Alembic commands ###
